### ISSUE TITLE
Download logs are static as of 5/28/2015

### ISSUE THREAD

**Issue by alforj** [metacran/cranlogs#10]
For all packages accessed by cran_downloads() the logs stop as of 5/28.

![image](https://cloud.githubusercontent.com/assets/6611693/8019880/c0e85400-0c32-11e5-9b36-2ddf8f6ba15f.png)

**Comment by gaborcsardi** [comment]
Yes, unfortunately there is no new from R Studio. :( They said it was unintended and they'll fix it by the en of next week.....

**Comment by gaborcsardi** [comment]
IT is working again now. Unfortunately about one week is lost.
