### ISSUE TITLE
0 downloads for 2018-04-06 and 2018-04-07

### ISSUE THREAD

**Issue by vonjd** [metacran/cranlogs#26]
Although the corresponding log files are available I only get 0 downloads for all packages (also the big ones) for those dates.

Thank you

**Comment by gaborcsardi** [comment]
Thanks! 2018-04-06 is there (now), but 2018-04-07 is missing from the server... I'll let them know...

**Comment by vonjd** [comment]
Did they answer? It is still not available...

**Comment by gaborcsardi** [comment]
they'll investigate, yeah... please remind me in a couple of days. thanks!

**Comment by vonjd** [comment]
Seems to be getting more and more unstable (not your package but the data delivery): 25'th and 26'th of April are missing too.

**Comment by gaborcsardi** [comment]
No, this is my script this time. It crashes for the 25th data,  so I need to fix it before continuing with the updates.

**Comment by vonjd** [comment]
Did they change the file format?

**Comment by gaborcsardi** [comment]
I don't know what the problem is.

**Comment by gaborcsardi** [comment]
OK, this  should  be fixed now.

I also added the missing 2018-04-07.

Thanks!

**Comment by vonjd** [comment]
Thank you, very good!

(so what was the problem?)

**Comment by gaborcsardi** [comment]
The parser loaded the whole file into memory and the machine ran out of memory.

**Comment by gaborcsardi** [comment]
Well, that  machine has 512MB of memory....
