### ISSUE TITLE
Day variable should be converted to Date

### ISSUE THREAD

**Issue by hadley** [metacran/cranlogs#5]

**Comment by gaborcsardi** [comment]
Ack.

**Comment by gaborcsardi** [comment]
So, apparently, some people use the package now: https://github.com/dgrtwo/cranview and I'll need to keep the API. :/

Anyway, I'll add a v2 API.

**Comment by gaborcsardi** [comment]
Well, no API v2, I just broke the API. Sorry about that.

**Comment by gaborcsardi** [comment]
Should work now.
