### ISSUE TITLE
List of all unique packages

### ISSUE THREAD

**Issue by arilamstein** [metacran/cranlogs#6]
Is there an way to get a list of all package names in the cran logs dataset?

**Comment by gaborcsardi** [comment]
Not with cranlogs, but easy with https://github.com/metacran/crandb: http://crandb.r-pkg.org/-/desc

With cranlogs we could only have tha packages that were downloaded at least once, otherwise they don't appear in the DB.

**Comment by arilamstein** [comment]
Thanks. Can you help me extract a vector of package names from that page?
I don't have a lot of experience with web scraping. Also, can you confirm
that that page is updated regularly?

To give you a feel for what I'm trying to do, I've recently made a few PRs
to the cranview project (https://github.com/dgrtwo/cranview), which is a
shiny app to show CRAN package download stats.

I think that that project would be improved if there was autocomplete for
the package names. But to support that feature, I would first need to have
a list of all possible names of R packages.

**Comment by arilamstein** [comment]
Gabor,

Sorry - please ignore my last comment. In my email client it looked like
there was only 1 link in your message, which went to a page of JSON. I
missed that you also wrote a package for that.

Sorry!

**Comment by gaborcsardi** [comment]
No worries. Do you have an idea why the shiny app is updates so slowly? It is a nice app, I am just not really convinced by the response time of shiny in general..... anyway, tell me if you have any trouble.

**Comment by arilamstein** [comment]
Thanks Gabor. I am not sure about why the app updates so slowly. I am new to shiny myself.

I thought that I would be able to use `list_packages()` to get the names of all packages, but I'm getting an error when I try to increase the limit to include all packages:
```
list_packages(from = "", limit = .Machine$integer.max, archived = FALSE)
Error in robust_q(service, url, fun, args, servers, odds, timeout_multiplier = timeout_multiplier *  : 
                      Cannot do query '/-/desc?start_key=""&limit=2147483647'.
```

Is there a better way to get a list of all package names?

**Comment by gaborcsardi** [comment]
Yes, this is clumsy, I didn't think about this use case. I think it is better to take the package names from the raw JSON API, so you don't need the crandb package (only the `httr` and `jsonlite` packages):

```R
names(httr::content(httr::GET("http://crandb.r-pkg.org/-/desc")))
```

**Comment by gaborcsardi** [comment]
To answer a previous question, yes it is kept up to date, and it is updated every minute.

**Comment by arilamstein** [comment]
Thanks Gabor. I think that this allowed me to greatly improve the app. You
can see my PR here: https://github.com/dgrtwo/cranview/pull/5.

My first PR was accepted pretty quickly. I'll wait to see if my last two
PRs are accepted. If they are, the only remaining change I'd like to make
is automatically setting the x-axis.
