### ISSUE TITLE
Some way of getting top n packages?

### ISSUE THREAD

**Issue by hadley** [metacran/cranlogs#8]

**Comment by gaborcsardi** [comment]
There is limited support for it in the JSON API: https://github.com/metacran/cranlogs.app#top-downloaded-packages-topperiodcount

I can extend it to more packages, or more flexible periods if you need that. The fixed periods are pre-calculated, so the queries are fast. Arbitrary periods will be somewhat slower.

Last week's data is also here: http://www.r-pkg.org/

Anyway, I'll add support for it to the R package in a sec.

**Comment by hadley** [comment]
Thanks!
